@extends('admin.layout')
@section('content')
<style>
    .admin-page-card { border:0; box-shadow:0 10px 30px rgba(24,39,75,.05); border-radius:18px; }
    .admin-toolbar { background:#f5f8ff; border:1px solid #e8edf7; border-radius:14px; padding:12px 16px; }
    .admin-table thead th { background:#f8f9ff; color:#475569; font-size:.75rem; letter-spacing:.04em; text-transform:uppercase; white-space:nowrap; }
    .admin-table tbody td { font-size:.87rem; vertical-align:middle; }
    .modal-content { border-radius:18px; border:0; }
</style>
@php
$fields = [
 'visiteurs' => [['name'=>'name','label'=>'Nom','type'=>'text','required'=>true],['name'=>'company','label'=>'Entreprise','type'=>'text'],['name'=>'phone','label'=>'Téléphone','type'=>'text'],['name'=>'purpose','label'=>'Motif','type'=>'text'],['name'=>'host','label'=>'Personne visitée','type'=>'text'],['name'=>'check_in_at','label'=>'Arrivée','type'=>'datetime-local'],['name'=>'check_out_at','label'=>'Départ','type'=>'datetime-local'],['name'=>'status','label'=>'Statut','type'=>'select','options'=>['expected'=>'Attendu','inside'=>'Sur place','completed'=>'Terminé','cancelled'=>'Annulé']],['name'=>'notes','label'=>'Notes','type'=>'textarea']],
 'appels' => [['name'=>'contact_name','label'=>'Contact','type'=>'text','required'=>true],['name'=>'phone','label'=>'Téléphone','type'=>'text'],['name'=>'subject','label'=>'Objet','type'=>'text'],['name'=>'direction','label'=>'Sens','type'=>'select','options'=>['incoming'=>'Entrant','outgoing'=>'Sortant']],['name'=>'call_at','label'=>'Date et heure','type'=>'datetime-local'],['name'=>'duration','label'=>'Durée (minutes)','type'=>'number'],['name'=>'status','label'=>'Statut','type'=>'select','options'=>['planned'=>'Planifié','completed'=>'Terminé','missed'=>'Manqué']],['name'=>'notes','label'=>'Notes','type'=>'textarea']],
 'courriers' => [['name'=>'reference','label'=>'Référence','type'=>'text','required'=>true],['name'=>'type','label'=>'Type','type'=>'select','options'=>['incoming'=>'Arrivée','outgoing'=>'Départ']],['name'=>'subject','label'=>'Objet','type'=>'text','required'=>true],['name'=>'sender','label'=>'Expéditeur','type'=>'text'],['name'=>'recipient','label'=>'Destinataire','type'=>'text'],['name'=>'received_at','label'=>'Date','type'=>'date'],['name'=>'status','label'=>'Statut','type'=>'select','options'=>['received'=>'Reçu','in_progress'=>'En traitement','processed'=>'Traité','archived'=>'Archivé']],['name'=>'file','label'=>'Pièce jointe','type'=>'file'],['name'=>'notes','label'=>'Notes','type'=>'textarea']],
 'reunions' => [['name'=>'title','label'=>'Titre','type'=>'text','required'=>true],['name'=>'location','label'=>'Lieu','type'=>'text'],['name'=>'starts_at','label'=>'Début','type'=>'datetime-local'],['name'=>'ends_at','label'=>'Fin','type'=>'datetime-local'],['name'=>'organizer','label'=>'Organisateur','type'=>'text'],['name'=>'attendees','label'=>'Participants','type'=>'textarea'],['name'=>'status','label'=>'Statut','type'=>'select','options'=>['planned'=>'Planifiée','held'=>'Tenue','cancelled'=>'Annulée']],['name'=>'minutes','label'=>'Compte-rendu','type'=>'textarea']],
 'documents' => [['name'=>'title','label'=>'Titre','type'=>'text','required'=>true],['name'=>'category','label'=>'Catégorie','type'=>'text'],['name'=>'document_date','label'=>'Date du document','type'=>'date'],['name'=>'status','label'=>'Statut','type'=>'select','options'=>['active'=>'Actif','archived'=>'Archivé']],['name'=>'description','label'=>'Description','type'=>'textarea'],['name'=>'file','label'=>'Fichier','type'=>'file']]
][$module];
@endphp
<div class="card admin-page-card mb-6"><div class="card-body p-6"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-4"><div><div class="text-uppercase text-muted fs-8 fw-bold ls-1">Administration</div><h3 class="fs-2 fw-bold text-dark mb-1">{{ $config['title'] }}</h3><p class="text-muted mb-0">{{ $config['description'] }}</p></div><div class="d-flex gap-2"><a href="{{ route('admin.administration') }}" class="btn btn-light btn-sm px-4">Retour</a><button class="btn btn-primary btn-sm px-4" data-bs-toggle="modal" data-bs-target="#recordModal">Nouveau</button></div></div></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="admin-toolbar mb-5 d-flex flex-wrap align-items-center justify-content-between gap-3"><div class="d-flex align-items-center gap-2"><i class="bi bi-grid-3x3-gap text-primary"></i><span class="fw-semibold text-dark">Registre administratif</span><span class="badge badge-light-primary">{{ $records->total() }} enregistrement(s)</span></div><span class="text-muted small">Dernières opérations en premier</span></div>
<div class="card admin-page-card"><div class="card-body table-responsive"><table class="table admin-table align-middle"><thead><tr><th>Résumé</th><th>Statut</th><th>Date de création</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($records as $record)
<tr><td><div class="fw-bold">{{ $record->title ?? $record->name ?? $record->contact_name ?? $record->subject ?? $record->reference }}</div><div class="text-muted small">{{ $record->company ?? $record->phone ?? $record->location ?? $record->category ?? '' }}</div>@if($record->file_path)<a class="small" target="_blank" href="{{ Storage::disk('public')->url($record->file_path) }}">Ouvrir le fichier</a>@endif</td><td><span class="badge badge-light-primary">{{ $record->status }}</span></td><td>{{ optional($record->created_at)->format('d/m/Y H:i') }}</td><td class="text-end"><button class="btn btn-sm btn-light" data-bs-toggle="modal" data-bs-target="#editModal{{ $record->id }}">Modifier</button><form class="d-inline" method="POST" action="{{ route('admin.administration.destroy', [$module,$record->id]) }}" onsubmit="return confirm('Supprimer cet enregistrement ?')">@csrf @method('DELETE')<button class="btn btn-sm btn-light-danger">Supprimer</button></form></td></tr>
<div class="modal fade" id="editModal{{ $record->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST" enctype="multipart/form-data" action="{{ route('admin.administration.update', [$module,$record->id]) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Modifier</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3">@foreach($fields as $field)<div class="{{ in_array($field['type'],['textarea']) ? 'col-12' : 'col-md-6' }}"><label class="form-label">{{ $field['label'] }}</label>@if($field['type']==='textarea')<textarea name="{{ $field['name'] }}" class="form-control">{{ $record->{$field['name']} }}</textarea>@elseif($field['type']==='select')<select name="{{ $field['name'] }}" class="form-select">@foreach($field['options'] as $value=>$label)<option value="{{ $value }}" @selected($record->{$field['name']}===$value)>{{ $label }}</option>@endforeach</select>@else<input type="{{ $field['type'] }}" name="{{ $field['name'] }}" value="{{ $field['type']==='datetime-local' ? optional($record->{$field['name']})->format('Y-m-d\TH:i') : $record->{$field['name']} }}" class="form-control" @required($field['required'] ?? false)>@endif</div>@endforeach</div><div class="modal-footer"><button class="btn btn-primary">Enregistrer</button></div></form></div></div></div>
@empty<tr><td colspan="4" class="text-center text-muted py-10">Aucun enregistrement.</td></tr>@endforelse
</tbody></table></div><div class="card-footer">{{ $records->links() }}</div></div>
<div class="modal fade" id="recordModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST" enctype="multipart/form-data" action="{{ route('admin.administration.store', $module) }}">@csrf<div class="modal-header"><h5 class="modal-title">Ajouter</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3">@foreach($fields as $field)<div class="{{ in_array($field['type'],['textarea']) ? 'col-12' : 'col-md-6' }}"><label class="form-label">{{ $field['label'] }}</label>@if($field['type']==='textarea')<textarea name="{{ $field['name'] }}" class="form-control"></textarea>@elseif($field['type']==='select')<select name="{{ $field['name'] }}" class="form-select">@foreach($field['options'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select>@else<input type="{{ $field['type'] }}" name="{{ $field['name'] }}" class="form-control" @required($field['required'] ?? false)>@endif</div>@endforeach</div><div class="modal-footer"><button class="btn btn-primary">Enregistrer</button></div></form></div></div></div>
@endsection
