<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8"><title>Devis {{ $quote->reference ?: '' }}</title>
<style>
@page{margin:18mm 16mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#555;font-size:12px;margin:0}.clearfix:after{content:"";display:table;clear:both}.header{border-bottom:1px solid #aaa;padding:8px 0 14px;margin-bottom:22px}.company{float:left;width:55%}.company h2{margin:0 0 8px;color:#17233d;font-size:20px}.company p{line-height:1.55;margin:0}.document{float:right;width:42%;text-align:right}.document h1{color:#0087c3;font-size:27px;font-weight:400;margin:0 0 10px}.document p{line-height:1.6;margin:0}.block{margin-bottom:18px}.client{border-left:6px solid #0087c3;padding:7px 0 7px 12px;line-height:1.55}.client strong{font-size:15px;color:#222}.subject{margin-top:10px}.items{width:100%;border-collapse:collapse;margin-top:18px}.items th{background:#eee;padding:11px 8px;text-align:center;font-weight:400;border-bottom:1px solid white}.items td{background:#f7f7f7;padding:10px 8px;border-bottom:1px solid white}.items .desc{text-align:left}.items .center{text-align:center}.items .right{text-align:right;white-space:nowrap}.totals{width:40%;margin:18px 0 0 auto;border-collapse:collapse}.totals td{padding:8px 10px;text-align:right;border-top:1px solid #ddd}.totals tr:last-child td{color:#168b47;font-size:16px;border-top:1px solid #168b47}.notes{border-left:6px solid #0087c3;padding-left:12px;margin-top:22px}.footer{border-top:1px solid #aaa;color:#777;text-align:center;margin-top:38px;padding-top:10px;font-size:10px}@media print{.no-print{display:none}}
</style>
</head>
<body>
<header class="header clearfix"><div class="company"><h2>{{ $company?->name ?: 'Diagoma ERP' }}</h2><p>{{ data_get($company?->settings, 'address') ?: 'Adresse de l’entreprise' }}<br>Tél : {{ data_get($company?->settings, 'phone') ?: '-' }}<br>Email : {{ data_get($company?->settings, 'email') ?: '-' }}<br>NIF : {{ data_get($company?->settings, 'nif') ?: '-' }}</p></div><div class="document"><h1>DEVIS N° {{ $quote->reference ?: $quote->id }}</h1><p>Date : {{ optional($quote->quote_date)->format('d/m/Y') }}<br>Validité : {{ optional($quote->due_date)->format('d/m/Y') ?: '-' }}<br>Statut : {{ $quote->status === 'validated' ? 'Validé' : 'En attente' }}</p></div></header>
<div class="block client"><strong>Client</strong><br>{{ $client?->name ?: $quote->client_name }}<br>{{ $client?->address ?: '-' }}<br>Tél : {{ $client?->phone ?: '-' }}<br>Email : {{ $client?->email ?: '-' }}<div class="subject"><strong>Objet :</strong> {{ $quote->subject ?: '-' }}</div></div>
<table class="items"><thead><tr><th>Article</th><th>Catégorie</th><th>Qté</th><th>Unité</th><th>Prix unitaire HT</th><th>Total HT</th></tr></thead><tbody>@foreach($quote->lines as $line)<tr><td class="desc">{{ $line['item_name'] ?? '-' }}</td><td class="desc">{{ $line['category_name'] ?? '-' }}</td><td class="center">{{ $line['quantity'] ?? 0 }}</td><td class="center">{{ $line['unit'] ?? '-' }}</td><td class="right">{{ money($line['unit_price'] ?? 0) }}</td><td class="right">{{ money((float)($line['quantity'] ?? 0)*(float)($line['unit_price'] ?? 0)) }}</td></tr>@endforeach</tbody></table>
<table class="totals"><tr><td>Total HT</td><td>{{ money($quote->total_ht) }}</td></tr>@if($quote->total_discount > 0)<tr><td>Remise</td><td>- {{ money($quote->total_discount) }}</td></tr>@endif<tr><td>TVA ({{ $quote->tax_rate }}%)</td><td>{{ money($quote->tax_amount) }}</td></tr><tr><td><strong>Total TTC</strong></td><td><strong>{{ money($quote->total_ttc) }}</strong></td></tr></table>
<div class="notes"><strong>Conditions</strong><br>Termes de paiement : {{ $quote->payment_terms ?: '-' }}<br>Termes de livraison : {{ $quote->delivery_terms ?: '-' }}<br>Lieu de livraison : {{ $quote->delivery_location ?: '-' }}</div>
<footer class="footer">{{ $company?->name ?: 'Diagoma ERP' }} – Document généré le {{ now()->format('d/m/Y à H:i') }}</footer><script>window.print()</script>
</body></html>
