@extends('admin.layout')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-5"><div><div class="text-uppercase text-muted fs-8 fw-bold">Commercial / Stock</div><h2 class="fs-2 fw-bold mb-1">Nouvelle entrée de stock</h2><p class="text-muted mb-0">Saisissez les articles réceptionnés et leur bénéfice.</p></div><a href="{{ route('admin.commercial.module', 'entrees-stock') }}" class="btn btn-light">Retour aux entrées</a></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card border-0"><div class="card-body"><form method="POST" action="{{ route('admin.commercial.stock-entries.store') }}">@csrf
<div class="d-flex justify-content-end mb-3"><label class="form-label me-3 mt-2">Date</label><input name="entry_date" type="date" class="form-control" style="max-width:220px" value="{{ now()->format('Y-m-d') }}" required></div>
<div class="table-responsive"><table class="table align-middle" id="stockLines"><thead><tr><th>Désignation</th><th>Article</th><th>Unité</th><th>Quantité *</th><th>Prix d'achat</th><th>Bénéfice/unité</th><th>Total (achat)</th><th></th></tr></thead><tbody></tbody></table></div>
<button type="button" class="btn btn-light-primary" id="addStockLine">Ajouter une ligne</button><div class="row justify-content-end mt-5"><div class="col-md-4"><div class="d-flex justify-content-between"><span>Bénéfice total :</span><strong id="stockProfit">0,00 {{ currency_symbol() }}</strong></div><div class="d-flex justify-content-between"><span>Marge :</span><strong id="stockMargin">0%</strong></div><div class="d-flex justify-content-between fs-3 mt-3"><span>Total (achat) :</span><strong id="stockTotal">0,00 {{ currency_symbol() }}</strong></div></div></div><button class="btn btn-primary mt-5">Enregistrer l’entrée</button></form></div></div>
<template id="stockLineTemplate"><tr><td><input name="lines[__INDEX__][designation]" class="form-control" required></td><td><input name="lines[__INDEX__][article]" class="form-control"></td><td><input name="lines[__INDEX__][unit]" class="form-control" placeholder="Unité"></td><td><input name="lines[__INDEX__][quantity]" type="number" min="0.001" step="0.001" value="1" class="form-control stock-quantity" required></td><td><input name="lines[__INDEX__][purchase_price]" type="number" min="0" step="0.01" value="0" class="form-control stock-price" required></td><td><input name="lines[__INDEX__][profit_per_unit]" type="number" min="0" step="0.01" value="0" class="form-control stock-profit-unit"></td><td class="stock-line-total">0,00 {{ currency_symbol() }}</td><td><button type="button" class="btn btn-light-danger remove-stock-line">&times;</button></td></tr></template>
@push('scripts')<script>
(() => {const body=document.querySelector('#stockLines tbody'),tpl=document.getElementById('stockLineTemplate'),money=v=>window.formatMoney(Number(v||0));const recalc=()=>{let total=0,profit=0;body.querySelectorAll('tr').forEach(row=>{const q=Number(row.querySelector('.stock-quantity').value)||0,p=Number(row.querySelector('.stock-price').value)||0,b=Number(row.querySelector('.stock-profit-unit').value)||0;total+=q*p;profit+=q*b;row.querySelector('.stock-line-total').textContent=money(q*p);});document.getElementById('stockTotal').textContent=money(total);document.getElementById('stockProfit').textContent=money(profit);document.getElementById('stockMargin').textContent=(total?((profit/total)*100).toFixed(2):0)+'%';};const add=()=>{body.insertAdjacentHTML('beforeend',tpl.innerHTML.replaceAll('__INDEX__',body.children.length));recalc();};document.getElementById('addStockLine').addEventListener('click',add);body.addEventListener('input',recalc);body.addEventListener('click',e=>{if(e.target.closest('.remove-stock-line')){e.target.closest('tr').remove();recalc();}});add();})();
</script>@endpush
@endsection
