@extends('admin.layout')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-5"><div><div class="text-uppercase text-muted fs-8 fw-bold">Commercial / Devis</div><h2 class="fs-2 fw-bold mb-1">{{ isset($quote) ? 'Modifier un devis' : 'Créer un devis' }}</h2><p class="text-muted mb-0">Le devis sera enregistré en attente de validation.</p></div><a href="{{ route('admin.commercial.module', 'devis') }}" class="btn btn-light">Retour</a></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ isset($quote) ? route('admin.commercial.quotes.update', $quote) : route('admin.commercial.quotes.store') }}" id="quoteForm">@csrf @if(isset($quote)) @method('PUT') @endif
<div class="card border-0 mb-5"><div class="card-header border-0"><h3 class="card-title">Informations générales</h3></div><div class="card-body"><div class="row g-4">
    <div class="col-md-6"><label class="form-label required">Client</label><select name="client_id" class="form-select" required><option value="">Sélectionner</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected(isset($quote) && $quote->client_id === $client->id)>{{ $client->name }} ({{ $client->phone ?: '000' }})</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label required">Date de création</label><input type="date" name="quote_date" value="{{ isset($quote) ? $quote->quote_date->format('Y-m-d') : now()->format('Y-m-d') }}" class="form-control" required></div>
    <div class="col-md-3"><label class="form-label">Date limite</label><input type="date" name="due_date" value="{{ isset($quote) && $quote->due_date ? $quote->due_date->format('Y-m-d') : now()->addMonth()->format('Y-m-d') }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Termes de paiements</label><input name="payment_terms" value="{{ $quote->payment_terms ?? '' }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Termes de livraison</label><input name="delivery_terms" value="{{ $quote->delivery_terms ?? '' }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Lieu de livraison</label><input name="delivery_location" value="{{ $quote->delivery_location ?? '' }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Mode de paiement</label><select name="payment_method" class="form-select"><option value="">Sélectionner...</option>@foreach(['Espèces','Chèque','Virement','Carte bancaire'] as $method)<option value="{{ $method }}" @selected(isset($quote) && $quote->payment_method === $method)>{{ $method }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Objet</label><textarea name="subject" class="form-control" rows="1" placeholder="Objet du devis">{{ $quote->subject ?? '' }}</textarea></div>
</div></div></div>
<div class="card border-0 mb-5"><div class="card-header border-0 d-flex justify-content-between align-items-center"><h3 class="card-title">Articles / services</h3><button type="button" class="btn btn-sm btn-light-primary" id="addQuoteLine">Ajouter une ligne</button></div><div class="card-body"><div class="alert alert-light-primary d-flex align-items-center py-3 mb-5"><i class="ki-duotone ki-information-5 fs-2 me-3"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i><span>Choisissez un type pour proposer les éléments du catalogue. La désignation reste toujours saisissable librement.</span></div><div class="table-responsive"><table class="table table-bordered align-middle" id="quoteLines"><thead><tr><th style="min-width: 130px;">Type</th><th style="min-width: 260px;">Désignation</th><th>Quantité</th><th>Prix unitaire</th><th></th></tr></thead><tbody></tbody></table></div>
    <div class="row justify-content-end mt-5"><div class="col-md-5 col-lg-4">
        <div class="d-flex justify-content-between mb-2"><span>Total HT</span><strong id="totalHt">0,00 XOF</strong></div>
        <div class="d-flex justify-content-between align-items-center mb-2"><label for="globalDiscount" class="mb-0">Remise</label><div class="input-group input-group-sm w-50"><input type="number" min="0" step="0.01" value="{{ $quote->total_discount ?? 0 }}" name="total_discount" id="globalDiscount" class="form-control"><span class="input-group-text">XOF</span></div></div>
        <div class="d-flex justify-content-between mb-2"><span>Montant net HT</span><strong id="netHt">0,00 XOF</strong></div>
        <div class="d-flex justify-content-between align-items-center mb-2"><label for="taxRate" class="mb-0">TVA</label><select name="tax_rate" id="taxRate" class="form-select form-select-sm w-50"><option value="0" @selected(($quote->tax_rate ?? 0) == 0)>Aucune taxe (0%)</option><option value="18" @selected(($quote->tax_rate ?? 0) == 18)>Appliquer la TVA (18%)</option></select></div>
        <div class="d-flex justify-content-between mb-2"><span>TVA</span><strong id="taxAmount">0,00 XOF</strong></div><div class="separator my-3"></div>
        <div class="d-flex justify-content-between fs-3"><strong>Total TTC</strong><strong id="totalTtc">0,00 XOF</strong></div>
    </div></div>
</div></div>
<div class="d-flex justify-content-end gap-3"><a href="{{ route('admin.commercial.module', 'devis') }}" class="btn btn-light">Annuler</a><button class="btn btn-primary" type="submit">Enregistrer en attente de validation</button></div>
</form>
<datalist id="quoteArticlesList">@foreach($quoteArticles as $article)<option value="{{ $article['name'] }}" label="{{ trim(($article['article'] ?: '') . (($article['unit'] ?? '') ? ' - ' . $article['unit'] : '')) }}"></option>@endforeach</datalist>
<datalist id="quoteServicesList">@foreach($quoteServices as $service)<option value="{{ $service->name }}" data-price="{{ $service->price }}" label="{{ $service->unit ?: 'Service' }}"></option>@endforeach</datalist>
<template id="quoteLineTemplate"><tr><td><select class="form-select line-type" name="lines[__INDEX__][item_type]" required><option value="article">Article</option><option value="service">Service</option></select></td><td><input class="form-control line-name" name="lines[__INDEX__][item_name]" list="quoteArticlesList" placeholder="Choisir ou saisir une désignation" required></td><td><input class="form-control line-quantity" name="lines[__INDEX__][quantity]" type="number" min="0.001" step="0.001" value="1" required></td><td><input class="form-control line-price" name="lines[__INDEX__][unit_price]" type="number" min="0" step="0.01" value="0" required></td><td><button type="button" class="btn btn-light-danger remove-quote-line">&times;</button></td></tr></template>
<script>
(() => { const body=document.querySelector('#quoteLines tbody'), tpl=document.getElementById('quoteLineTemplate'); const money=v=>Number(v||0).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' XOF'; const setCatalog=(row,type)=>{const name=row.querySelector('.line-name');name.setAttribute('list',type==='service'?'quoteServicesList':'quoteArticlesList');if(type==='service'){const option=[...document.querySelectorAll('#quoteServicesList option')].find(item=>item.value.toLowerCase()===name.value.trim().toLowerCase());if(option && !Number(row.querySelector('.line-price').value)){row.querySelector('.line-price').value=option.dataset.price||0;}}}; const add=(line=null)=>{const index=body.children.length;body.insertAdjacentHTML('beforeend',tpl.innerHTML.replaceAll('__INDEX__',index));const row=body.lastElementChild;const type=line?.item_type==='service'?'service':'article';row.querySelector('.line-type').value=type;setCatalog(row,type);if(line){row.querySelector('.line-name').value=line.item_name||'';row.querySelector('.line-quantity').value=line.quantity||1;row.querySelector('.line-price').value=line.unit_price||0;}}; const totals=()=>{let ht=0;body.querySelectorAll('tr').forEach(row=>{ht+=(Number(row.querySelector('.line-quantity').value)||0)*(Number(row.querySelector('.line-price').value)||0);});const discount=Math.min(ht,Number(document.getElementById('globalDiscount').value)||0),net=ht-discount,tax=net*(Number(document.getElementById('taxRate').value)||0)/100;document.getElementById('totalHt').textContent=money(ht);document.getElementById('netHt').textContent=money(net);document.getElementById('taxAmount').textContent=money(tax);document.getElementById('totalTtc').textContent=money(net+tax);}; document.getElementById('addQuoteLine').addEventListener('click',()=>add()); body.addEventListener('change',e=>{if(e.target.matches('.line-type')){setCatalog(e.target.closest('tr'),e.target.value);}if(e.target.matches('.line-name')){setCatalog(e.target.closest('tr'),e.target.closest('tr').querySelector('.line-type').value);}totals();}); body.addEventListener('click',e=>{if(e.target.closest('.remove-quote-line')){e.target.closest('tr').remove();totals();}}); document.getElementById('quoteForm').addEventListener('input',totals);document.getElementById('taxRate').addEventListener('change',totals); const lines=@json(isset($quote) ? $quote->lines : []); if(lines.length){lines.forEach(add);}else{add();} totals(); })();
</script>
@endsection
