@extends('admin.layout')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-5"><div><div class="text-uppercase text-muted fs-8 fw-bold">Commercial / Stock</div><h2 class="fs-2 fw-bold mb-1">Nouvelle sortie de stock</h2><p class="text-muted mb-0">Saisissez les articles et quantités sortis.</p></div><a href="{{ route('admin.commercial.module', 'sorties-stock') }}" class="btn btn-light">Retour aux sorties</a></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card border-0"><div class="card-body"><form method="POST" action="{{ route('admin.commercial.stock-exits.store') }}">@csrf
<div class="d-flex justify-content-end mb-3"><label class="form-label me-3 mt-2">Date</label><input name="exit_date" type="date" class="form-control" style="max-width:220px" value="{{ now()->format('Y-m-d') }}" required></div>
<div class="table-responsive"><table class="table align-middle" id="stockExitLines"><thead><tr><th>Article</th><th>Unité</th><th>Disponible</th><th>Quantité sortie *</th><th>Prix achat</th><th>Valeur</th><th></th></tr></thead><tbody></tbody></table></div>
<button type="button" class="btn btn-light-primary" id="addStockExitLine">Ajouter une ligne</button><div class="d-flex justify-content-end fs-3 mt-5"><strong>Total sortie : <span id="stockExitTotal">0,00 {{ currency_symbol() }}</span></strong></div><button class="btn btn-primary mt-5">Enregistrer la sortie</button></form></div></div>
<template id="stockExitLineTemplate"><tr><td><select name="lines[__INDEX__][stock_entry_line_id]" class="form-select exit-line-select" required><option value="">Sélectionner un article</option>@foreach($stockLines as $line)<option value="{{ $line->id }}" data-available="{{ (float) $line->quantity - (float) ($usedQuantities[$line->id] ?? 0) }}" data-price="{{ $line->purchase_price }}" data-unit="{{ $line->unit }}">{{ $line->designation }}{{ $line->article ? ' - '.$line->article : '' }} (stock: {{ number_format((float) $line->quantity - (float) ($usedQuantities[$line->id] ?? 0), 3, ',', ' ') }})</option>@endforeach</select></td><td class="exit-unit">-</td><td class="exit-available">-</td><td><input name="lines[__INDEX__][quantity]" type="number" min="0.001" step="0.001" class="form-control exit-quantity" required></td><td class="exit-price">0.00</td><td class="exit-total">0.00</td><td><button type="button" class="btn btn-light-danger remove-exit-line">&times;</button></td></tr></template>
@push('scripts')<script>
(() => {const body=document.querySelector('#stockExitLines tbody'),tpl=document.getElementById('stockExitLineTemplate'),money=v=>window.formatMoney(Number(v||0));const recalc=()=>{let total=0;body.querySelectorAll('tr').forEach(row=>{const option=row.querySelector('.exit-line-select').selectedOptions[0],q=Number(row.querySelector('.exit-quantity').value)||0,p=Number(option?.dataset.price)||0;row.querySelector('.exit-unit').textContent=option?.dataset.unit||'-';row.querySelector('.exit-available').textContent=option?.dataset.available||'-';row.querySelector('.exit-price').textContent=money(p);row.querySelector('.exit-total').textContent=money(q*p);total+=q*p;});document.getElementById('stockExitTotal').textContent=money(total);};const add=()=>{body.insertAdjacentHTML('beforeend',tpl.innerHTML.replaceAll('__INDEX__',body.children.length));recalc();};document.getElementById('addStockExitLine').addEventListener('click',add);body.addEventListener('change',recalc);body.addEventListener('input',recalc);body.addEventListener('click',e=>{if(e.target.closest('.remove-exit-line')){e.target.closest('tr').remove();recalc();}});add();})();
</script>@endpush
@endsection
