@extends('admin.layout')

@section('content')
<div class="mb-5"><div class="text-muted fs-7">Accueil / Compte</div><h1 class="page-heading mb-0">Mon profil</h1></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

<div class="card border-0 overflow-hidden mb-5">
    <div class="card-body p-5 p-lg-8"><div class="d-flex flex-wrap align-items-center gap-5">
        <div class="position-relative"><img src="{{ $user->avatar_path ? asset('storage/' . $user->avatar_path) : asset('assets/media/avatars/300-1.jpg') }}" alt="Photo de profil" class="rounded-3" style="width:150px;height:150px;object-fit:cover;"><span class="position-absolute bottom-0 end-0 bg-success border border-3 border-white rounded-circle" style="width:20px;height:20px;"></span></div>
        <div class="flex-grow-1"><h2 class="mb-2">{{ $user->name }}</h2><div class="text-muted mb-1"><i class="bi bi-person me-2"></i>{{ $user->role?->label ?? 'Administrateur' }}</div><div class="text-muted mb-1"><i class="bi bi-envelope me-2"></i>{{ $user->email }}</div><div class="text-muted"><i class="bi bi-telephone me-2"></i>{{ $user->phone ?: 'Téléphone non renseigné' }}</div></div>
        <div class="text-muted text-end"><div class="fs-2 fw-bold text-primary">{{ $user->matricule ?: '9000' }}</div><div>Matricule</div></div>
    </div></div>
    <div class="card-footer p-0 border-top"><ul class="nav nav-tabs nav-line-tabs nav-stretch fs-6 fw-semibold px-4" id="profileTabs">
        <li class="nav-item"><a class="nav-link active" href="#personal">Informations personnelles</a></li><li class="nav-item"><a class="nav-link" href="#password">Mot de passe</a></li><li class="nav-item"><a class="nav-link" href="#payroll">Mes bulletins</a></li><li class="nav-item"><a class="nav-link" href="#leave">Congés</a></li><li class="nav-item"><a class="nav-link" href="#attendance">Présence</a></li><li class="nav-item"><a class="nav-link" href="#documents">Mes documents</a></li><li class="nav-item"><a class="nav-link" href="#timeline">Chronologie</a></li>
    </ul></div>
</div>

<section id="personal" class="profile-panel card border-0">
<div class="card-header"><h3 class="card-title">Informations personnelles</h3></div><div class="card-body">
<form method="POST" enctype="multipart/form-data" action="{{ route('admin.profile.update') }}">@csrf @method('PATCH')
<div class="row g-5">
<div class="col-12"><label class="form-label fw-semibold">Photo de profil</label><input type="file" name="avatar" class="form-control" accept="image/jpeg,image/png,image/webp"></div>
<div class="col-md-6"><label class="form-label">Nom complet</label><input name="name" value="{{ old('name',$user->name) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" name="email" value="{{ old('email',$user->email) }}" class="form-control" required></div>
<div class="col-md-6"><label class="form-label">Téléphone</label><input name="phone" value="{{ old('phone',$user->phone) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Contact d'urgence</label><input name="emergency_contact" value="{{ old('emergency_contact',$user->emergency_contact) }}" class="form-control"></div>
<div class="col-md-4"><label class="form-label">Sexe</label><select name="gender" class="form-select"><option value="">Sélectionner</option><option {{ $user->gender==='Male'?'selected':'' }}>Male</option><option {{ $user->gender==='Female'?'selected':'' }}>Female</option></select></div><div class="col-md-4"><label class="form-label">Date de naissance</label><input type="date" name="birth_date" value="{{ optional($user->birth_date)->format('Y-m-d') }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Situation matrimoniale</label><input name="marital_status" value="{{ old('marital_status',$user->marital_status) }}" class="form-control"></div>
<div class="col-md-6"><label class="form-label">Nom du père</label><input name="father_name" value="{{ old('father_name',$user->father_name) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Nom de la mère</label><input name="mother_name" value="{{ old('mother_name',$user->mother_name) }}" class="form-control"></div>
<div class="col-md-6"><label class="form-label">Qualification</label><input name="qualification" value="{{ old('qualification',$user->qualification) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Expérience professionnelle</label><input name="experience" value="{{ old('experience',$user->experience) }}" class="form-control"></div><div class="col-12"><label class="form-label">Remarque</label><textarea name="remark" class="form-control">{{ old('remark',$user->remark) }}</textarea></div>
<div class="col-12"><h4 class="border-bottom pb-3 mt-3">Adresse</h4></div><div class="col-md-6"><label class="form-label">Adresse actuelle</label><input name="address" value="{{ old('address',$user->address) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Adresse permanente</label><input name="permanent_address" value="{{ old('permanent_address',$user->permanent_address) }}" class="form-control"></div>
<div class="col-12"><h4 class="border-bottom pb-3 mt-3">Détails de compte en banque</h4></div><div class="col-md-6"><label class="form-label">Titre de compte</label><input name="account_title" value="{{ old('account_title',$user->account_title) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Nom de banque</label><input name="bank_name" value="{{ old('bank_name',$user->bank_name) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Succursale bancaire</label><input name="bank_branch" value="{{ old('bank_branch',$user->bank_branch) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Numéro de compte bancaire</label><input name="bank_account_number" value="{{ old('bank_account_number',$user->bank_account_number) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Code IFSC</label><input name="ifsc_code" value="{{ old('ifsc_code',$user->ifsc_code) }}" class="form-control"></div>
<div class="col-12"><h4 class="border-bottom pb-3 mt-3">Lien de médias sociaux</h4></div><div class="col-md-6"><label class="form-label">Facebook</label><input name="facebook_url" value="{{ old('facebook_url',$user->facebook_url) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Twitter</label><input name="twitter_url" value="{{ old('twitter_url',$user->twitter_url) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">LinkedIn</label><input name="linkedin_url" value="{{ old('linkedin_url',$user->linkedin_url) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Instagram</label><input name="instagram_url" value="{{ old('instagram_url',$user->instagram_url) }}" class="form-control"></div>
<div class="col-12"><h4 class="border-bottom pb-3 mt-3">Détails administratifs</h4></div><div class="col-md-4"><label class="form-label">Matricule</label><input name="matricule" value="{{ old('matricule',$user->matricule ?: '9000') }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Rôle</label><input value="{{ $user->role?->label ?? 'Super Admin' }}" class="form-control" disabled></div><div class="col-md-4"><label class="form-label">Fonction</label><input name="job_title" value="{{ old('job_title',$user->job_title) }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Services</label><input name="services" value="{{ old('services',$user->services) }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Responsable</label><input name="manager" value="{{ old('manager',$user->manager) }}" class="form-control"></div><div class="col-md-4"><label class="form-label">CNPS</label><input name="cnps" value="{{ old('cnps',$user->cnps) }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Salaire de base</label><input type="number" step="0.01" name="base_salary" value="{{ old('base_salary',$user->base_salary) }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Type de contrat</label><input name="contract_type" value="{{ old('contract_type',$user->contract_type) }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Poste de travail</label><input name="workstation" value="{{ old('workstation',$user->workstation) }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Emplacement</label><input name="location" value="{{ old('location',$user->location) }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Date d'enregistrement</label><input type="date" name="registered_at" value="{{ optional($user->registered_at)->format('Y-m-d') }}" class="form-control"></div>
</div><div class="text-end mt-5"><button class="btn btn-primary">Enregistrer les informations</button></div></form>
</div></section>
<section id="payroll" class="profile-panel card border-0 d-none">
<div class="card-header d-flex justify-content-between align-items-center"><h3 class="card-title">Mes bulletins de salaire</h3><span class="badge badge-light-primary">{{ $payrolls->count() }}</span></div>
<div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Période</th><th>Brut</th><th>Net à payer</th><th>Actions</th></tr></thead><tbody>
@forelse($payrolls as $payroll)
<tr><td>{{ \Carbon\Carbon::create()->month($payroll->month)->translatedFormat('F') }} {{ $payroll->year }}</td><td>{{ money($payroll->gross_salary) }}</td><td class="fw-bold">{{ money($payroll->net_salary) }}</td><td><a target="_blank" class="btn btn-sm btn-light-primary" href="{{ route('admin.rh.payroll.show', $payroll) }}">Voir / imprimer</a><a target="_blank" class="btn btn-sm btn-light ms-2" href="{{ route('admin.rh.payroll.pdf', $payroll) }}">PDF</a></td></tr>
@empty <tr><td colspan="4" class="text-center text-muted py-8">Aucun bulletin disponible.</td></tr>@endforelse
</tbody></table></div></div>
</section>

<section id="password" class="profile-panel card border-0 d-none"><div class="card-header"><h3 class="card-title">Mot de passe</h3></div><div class="card-body"><form method="POST" action="{{ route('admin.profile.password.update') }}">@csrf @method('PATCH')<div class="row g-5"><div class="col-md-6"><label class="form-label">Nouveau mot de passe</label><input type="password" name="password" class="form-control" minlength="8"></div><div class="col-md-6"><label class="form-label">Confirmation</label><input type="password" name="password_confirmation" class="form-control" minlength="8"></div></div><div class="text-end mt-5"><button class="btn btn-primary">Modifier le mot de passe</button></div></form></div></section>
@foreach([['leave','Congés','Les demandes et le solde de congés seront affichés ici.'],['attendance','Présence','L’historique des présences sera affiché ici.'],['documents','Mes documents','Les documents administratifs seront affichés ici.'],['timeline','Chronologie','L’activité récente du compte sera affichée ici.']] as [$id,$heading,$message])<section id="{{ $id }}" class="profile-panel card border-0 d-none"><div class="card-header"><h3 class="card-title">{{ $heading }}</h3></div><div class="card-body text-muted text-center py-10">{{ $message }}</div></section>@endforeach
@push('scripts')<script>document.querySelectorAll('#profileTabs a').forEach(function(tab){tab.addEventListener('click',function(e){e.preventDefault();document.querySelectorAll('#profileTabs a').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.profile-panel').forEach(x=>x.classList.add('d-none'));tab.classList.add('active');document.querySelector(tab.getAttribute('href')).classList.remove('d-none');});});</script>@endpush
@endsection
